### ISSUE TITLE
Start and End Radius or Angle

### ISSUE THREAD

**Issue by eblabs** [mamitko/Clothoid#3]
Hi,
Great work on this curve framework!

Just curious, do you have any suggestions on how to setup a Clothoid with a start and end point, and also start and end angles as well?
Thanks again!!
Eric

**Comment by mamitko** [comment]
Hi!
The first and the obviouse thing is that the coordinates of the start and end points does not matter, just the spatial distance between the points and the "change" of angle.
So you find a curvature rate than translate and rotate the clothod.

The problem is the finding curvature rate itself. I'm pretty sure you will have to do it numerically (as other fitting procedures you can find there) but as I see there are more than one degrees of freedom: 
1. the curvature rate itself
2. a params of the parametric equation of the clt (with the given curvaure rate) of the start and end points

I mean "for each" curvature rate you will have to TRY to find**  the two points*** with the given distance and difference of angle.

** numerecally as well
*** values of param of the parametric equuation of clothoid
